export const Tests = [
  {
    product: "spot",
    dataType: "klines",
    date: "2026-01",
    symbols: "btcusdt",
    intervals: "1h",
    expectedFiles: 1,
  },
  {
    product: "spot",
    dataType: "klines",
    date: "2026-01-01",
    symbols: "btcusdt",
    intervals: "4h",
    expectedFiles: 1,
  },
  {
    product: "usd-m",
    dataType: "markPriceKlines",
    date: "2025-01-01",
    symbols: "ethusdt",
    intervals: "4h",
    expectedFiles: 1,
  },
  {
    product: "coin-m",
    dataType: "metrics",
    date: "2025-01-01 2025-01-03",
    symbols: "dotusd_perp",
    intervals: "",
    expectedFiles: 1,
  },
  {
    product: "spot",
    dataType: "klines",
    date: "2024-05",
    symbols: "eosusdt dogeusdt",
    intervals: "1d",
    expectedFiles: 2,
  },
  {
    product: "spot",
    dataType: "klines",
    date: "2024-05",
    symbols: "eosusdt",
    intervals: "1d 1w",
    expectedFiles: 2,
  },
  {
    product: "spot",
    dataType: "klines",
    date: "2024-05 2024-07",
    symbols: "eosusdt dogeusdt",
    intervals: "1d 1w",
    expectedFiles: 4,
  },
  {
    product: "spot",
    dataType: "klines",
    date: "2023-12-15 2024-01-15",
    symbols: "xrpusdt",
    intervals: "1d",
    expectedFiles: 1,
  },
];